### Register
POST http://localhost:8080/api/v1/auth/register
Content-Type: application/json

{
  "firstName": "{{ firstName }}",
  "lastName": "{{ lastName }}",
  "email": "{{ email }}",
  "password": "{{ password }}",
  "role": "USER" 
}

### Login
POST http://localhost:8080/api/v1/auth/login
Content-Type: application/json

{
  "email": "{{ email }}",
  "password": "{{ password }}"
}

### Demo
GET http://localhost:8080/api/v1/demo
Authorization: Bearer {{ token }}