spring:
  application:
    name: jwt
  datasource:
    url:
    username:
    password:
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format-sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

logging:
  level:
    root: INFO

application:
  security:
    jwt:
      secret-key:
      expiration:
      refresh:
        expiration:
